import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-500`}
      >
        {children}

        {/* Load dependencies */}
        <Script
          src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://c20.live/script/chatbot-embed.js"
          strategy="afterInteractive"
        />

        {/* Initialize chatbot after scripts are ready */}
        <Script id="chatbot-init" strategy="afterInteractive">
          {`
            (function initChatbot() {
              if (window.initializeChatbot) {
                window.initializeChatbot("6846b28dd99fd94644626069");
                return;
              }

              let retries = 0;
              const maxRetries = 100; // 100 x 100ms = 10s
              const interval = setInterval(() => {
                if (window.initializeChatbot) {
                  window.initializeChatbot("6846b28dd99fd94644626069");
                  clearInterval(interval);
                } else if (++retries >= maxRetries) {
                  clearInterval(interval);
                  console.warn("Chatbot failed to initialize after 10s.");
                }
              }, 100);
            })();
          `}
        </Script>
      </body>
    </html>
  );
}
