import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script defer src="https://cdn.tailwindcss.com"></script>
        <script defer src="https://c20.live/script/chatbot-embed.js"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-500`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              document.addEventListener('DOMContentLoaded', function() {
                if (window.initializeChatbot) {
                  window.initializeChatbot("681e54d0506831086587f5c6");
                  return;
                }
                const checkInitialize = setInterval(function() {
                  if (window.initializeChatbot) {
                    window.initializeChatbot("681e54d0506831086587f5c6");
                    clearInterval(checkInitialize);
                  }
                }, 100);
                setTimeout(() => clearInterval(checkInitialize), 10000);
              });
            `,
          }}
        />
      </body>
    </html>
  );
}
