import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";

// Load Poppins font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // optional: adjust based on your usage
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Load marked.js */}
        <Script
          src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"
          strategy="afterInteractive"
        />

        {/* Load chatbot script and initialize */}
        <Script id="chatbot-loader" strategy="afterInteractive">
          {`
            (function () {
              const botId = "6847eb146584ec5f07dd2b04";
              const chatbotScript = document.createElement("script");
              chatbotScript.src = "https://c20.live/script/chatbot-embed.js";
              chatbotScript.defer = true;
              chatbotScript.onload = function () {
                if (window.initializeChatbot) {
                  window.initializeChatbot(botId);
                  return;
                }

                const checkInitialize = setInterval(function () {
                  if (window.initializeChatbot) {
                    window.initializeChatbot(botId);
                    clearInterval(checkInitialize);
                  }
                }, 100);

                setTimeout(() => clearInterval(checkInitialize), 10000);
              };
              document.head.appendChild(chatbotScript);
            })();
          `}
        </Script>
      </head>
      <body>{children}</body>
    </html>
  );
}
